MULTIARCH-4694: Enable insecure registries for mirror repositories
outrigger-project/multiarch-tuning-operator pull request #177
Opened 2024-07-17 00:08 UTC by AnnaZivkovic

2024-07-22 13:47 UTC, aleskandro requested changes
Hi @AnnaZivkovic, thanks!

This PR needs some work yet. There are two concurrent types of updates that can happen:

1. updating the insecure registries (let's say keeping constant the ITMS/IDMS/ICSPs): in this case, we need to loop through all the defined registries and set each of their mirrors to insecure if needed.
2. updating an ITMS/IDMS/ICSP: in this case we should look for its mirrors' conf. If a mirror is part of the insecureRegistries set, its 'insecure' field must be set to true.

We also need to cover this code with some test cases (both unit and integration).

Let's start from some unit cases that execute the changed functions given different initial conditions for the involved objects. For example:
1. No insecureRegistries
2. Insecure registries set. Add a new registry that is NOT insecure, with an insecure Mirror. Expectation: the registry has no insecure field, the mirror has.
3. Insecure registries set. Add a new registry that is insecure with a secure mirror. Expection: the registry has insecure set to true and the mirror has no insecure field.
4. Insecure registries set including registry Y; a registry X set with an insecure mirror Y. Remove the registry Y from the insecure registries and let the update go. We expect the registry Y is not anymore set in the main list, and the mirror's instance of registry Y for registry X has no inseucre field anymore.
5. Insecure registries set. Add a registry that is not in the insecure registries set, with mirrors not in the insecure registries set. Expectation: the registry is added with no insecure field and its mirrors have no insecure field either. The insecure registries are still set as they were initially.

2024-07-22 13:47 UTC, aleskandro commented on pkg/systemconfig/syncer.go
> +	rc.Mirrors = mirrorsFor(mirrors, pullType, rc.Insecure)
This function is called when a new ImageContentSource, ImageDigestMirrorSet or ImageTagMirrorSet is created, right?. You are setting insecure for all the mirrors to the same value as the mirrored registry.

If I remember and understand correctly, we should look for each mirror's specific conf in the 'first-level registry' (using `getRegistryConf`). If the getRegistryConf returns its conf and that conf has insecure=True, we should set that specific mirror to be insecure too.

2024-07-22 13:47 UTC, aleskandro commented on pkg/systemconfig/syncer.go
> +	rc.Mirrors = mirrorsFor(mirrors, pullType, rc.Insecure)
```suggestion
	rc.Mirrors = mirrorsFor(mirrors, pullType)
	trueValue := true
	for _, mirror := range rc.Mirrors {
	  if mrc, ok := s.registriesConfContent.getRegistryConf(mirror); ok && mrc.insecure != nil && *mrc.insecure == true {
	    mirror.Insecure = &trueValue
	  }
	}
	
```

2024-07-22 13:47 UTC, aleskandro commented on pkg/systemconfig/syncer.go
> +		}
This shouldn't happen only here, but for all the defined registries. Therefore, after the last for loop instead of nested in the insecure registries' one.

After you have that map filled, we need to loop through all the registries in registriesConfContent.

For each registry (maybe we can't loop through all the registries yet), for each mirror, if that mirror has a registryConf (use getRegistryConf) and it has insecure not nil and true, we set that mirror to insecure true.

2024-07-29 21:12 UTC, Prashanth684 commented on pkg/systemconfig/syncer.go
> +		}
it should be set only for allowed registries right? we still need to make sure we don't do it for blocked ones

2024-07-29 21:14 UTC, aleskandro commented on pkg/systemconfig/syncer.go
> +		}
I think we should do for them too. They are two independent configurations: blockedregistries will land into policy.json

2024-07-31 21:16 UTC, AnnaZivkovic commented on pkg/systemconfig/types.go
> +		mirrors = append(mirrors, mirrorFor(location, pullType, nil))
Is this an acceptable default value for mirror.Insecure?

2024-08-01 22:40 UTC, AnnaZivkovic commented
/retest-required

2024-08-05 21:29 UTC, AnnaZivkovic commented
/retest-required

2024-08-06 14:48 UTC, aleskandro commented on pkg/systemconfig/types.go
> +		mirrors = append(mirrors, mirrorFor(location, pullType, nil))
do we ever pass a non nil value to this function?

2024-08-06 14:58 UTC, aleskandro commented on pkg/systemconfig/syncer.go
> +			if allowedRegistriesMap[mirror.Location] {
```suggestion
			if _, ok := allowedRegistriesMap[mirror.Location]; ok {
```

2024-08-06 15:13 UTC, aleskandro commented on pkg/systemconfig/syncer.go
> +	}
Should we maybe move this to `mirrorsFor` (and have `mirrorsFor` as a method of `SystemConfigSyncer` rather than a function)?

Doing it here means that mirrorsFor will not be fully responsible for defining the mirrors but some other logic must be implemented 'always' after that method is called, violating "separation of concerns".

2024-08-06 15:25 UTC, aleskandro commented on pkg/systemconfig/syncer.go
>  	s.registriesConfContent.cleanupAllRegistryConfIfEmpty()
I see some value in having an increased in-memory complexity vs an increased processing complexity, but we are having this snippet of code copied over 4 times.

Also, we already have a lookup map to support this 'faster' lookup strategy.

Can we just do the following after `cleanupAllRegistryConfIfEmpty()` call, once the comment in https://github.com/openshift/multiarch-tuning-operator/pull/177/files#r1705717318 for mirrorsFor is addressed?:

```suggestion
	s.registriesConfContent.cleanupAllRegistryConfIfEmpty()
	for _, rc := range s.registriesConfContent.Registries {
		if len(rc.Mirrors) > 0 {
			rc.Mirrors = s.mirrorsFor(rc.mirrors, rc.mirrors[0].pullType)
		}
	}
```

2024-08-06 15:28 UTC, aleskandro commented on pkg/systemconfig/syncer.go
> +				mirror.Insecure = &trueValue
Mmm, even re-reading, we should set mirror.Insecure  to true only if mirror is in the insecureRegistries. This would set Insecure to true once any conf is previously set for that registry. 

I would really go ahead with:
1. https://github.com/openshift/multiarch-tuning-operator/pull/177/files#r1705717318
2. https://github.com/openshift/multiarch-tuning-operator/pull/177/files#r1705735790

2024-08-06 15:31 UTC, aleskandro commented on pkg/systemconfig/types.go
> +		mirrors = append(mirrors, mirrorFor(location, pullType, nil))
maybe, once this function becomes a method of SystemConfiSyncer (see https://github.com/openshift/multiarch-tuning-operator/pull/177/files#r1705717318)

```suggestion
		var insecure *bool = nil;
		if  s.registriesConfContent.getRegistryConf(mirror.Location); ok && mrc.Insecure != nil {
		 insecure = mrc.Insecure
		}
		mirrors = append(mirrors, mirrorFor(location, pullType, insecure))
```

2024-08-06 19:44 UTC, AnnaZivkovic commented
/retest-required

2024-08-06 19:55 UTC, aleskandro commented
@AnnaZivkovic the CI is blocked by https://github.com/openshift/release/pull/55145 (revert PR at https://github.com/openshift/release/pull/55260)

2024-08-09 11:58 UTC, aleskandro commented on pkg/systemconfig/syncer.go
> +		for _, mirror := range rc.Mirrors {
```suggestion
		for _, mirror := range rc.Mirrors {
			mirror.Insecure = nil // reset it everytime before syncing with the insecureRegistries set
```

2024-08-09 12:00 UTC, aleskandro reviewed
This looks good to me... Can we develop some integration or unit tests before merging?

2024-08-09 12:01 UTC, aleskandro commented
Also adding Lin for some premerge testing here:

/cc @lwan-wanglin

2024-08-09 20:54 UTC, AnnaZivkovic commented on pkg/systemconfig/syncer.go
> +		for _, mirror := range rc.Mirrors {
I was doing it [here](https://github.com/openshift/multiarch-tuning-operator/blob/b06240250b54e9dc9cae5f1c7b8ee36ecf89e722/pkg/systemconfig/syncer.go#L64-L66). That is where we are resetting everything else, but it requires an extra loop though the mirrors

2024-08-09 21:27 UTC, aleskandro commented on pkg/systemconfig/syncer.go
> +		for _, mirror := range rc.Mirrors {
oh, I lost that...

2024-08-13 01:07 UTC, lwan-wanglin commented
/test e2e-gcp-multi-operator

2024-08-13 03:03 UTC, lwan-wanglin commented
/test e2e-gcp-multi-operator

2024-08-13 09:55 UTC, lwan-wanglin commented
/test images

2024-08-13 11:26 UTC, lwan-wanglin commented
/test images

2024-08-14 02:16 UTC, lwan-wanglin commented
detailed test discussion is in slack channel: https://redhat-internal.slack.com/archives/C06ECDGH4LE/p1723550648966339

2024-08-15 23:29 UTC, AnnaZivkovic commented on pkg/systemconfig/syncer.go
> +			if mrc, ok := s.registriesConfContent.getRegistryConf(strings.Split(mirror.Location, "/")[0]); ok && mrc.Insecure != nil {
I would have used [string.TrimSuffix](https://pkg.go.dev/strings#TrimSuffix), but it only works if the _end_ of the string matches the suffix provided. 
`strings.TrimSuffix("virthost.cluster-01.okd.on.massopen.cloud:5000/localimages/local-release-image", "/") ---> virthost.cluster-01.okd.on.massopen.cloud:5000/localimages/local-release-image`

`strings.TrimSuffix("virthost.cluster-01.okd.on.massopen.cloud:5000/localimages/local-release-image", "/local-release-image") ---> virthost.cluster-01.okd.on.massopen.cloud:5000/localimages`

2024-08-16 17:53 UTC, aleskandro commented
I'm ok with this. I'd wait @lwan-wanglin's results again since we're not implementing tests here.

2024-08-18 13:55 UTC, aleskandro commented on pkg/systemconfig/syncer.go
> +			if mrc, ok := s.registriesConfContent.getRegistryConf(strings.Split(mirror.Location, "/")[0]); ok && mrc.Insecure != nil {
We cannot split and take the first part I believe as users can still set just a repo (or even a single image or tag) of a registry as insecure. I think we'd set insecure=True for a Mirror m if a insecure registry r exists such that strings.HasPrefix(m, r) or (r starts with a wildcard (*) and r without the * prefix is included in the first part of m before a slash (/) like you did with split)

Example:

insecure registry: myregistry.com/myallowedinsecurerepo/

Mirror that shouldn't be set as insecure: myregistry.com/myotherrepo

Mirror that should be set insecure:
myregistry.com/myallowedinsecurrepo/myomage:latest

Mirror that should be set insecure:
myregistry.com/myallowedinsecurrepo

(Note the leading slash in the insecure registry. The last mirror would not match if we don't remove it)


Another insecure registry setting can be 
- *.mydomain.tld

These mirrors should be set insecure too (wildcard condition above):
sub4.sub3.mydomain.tld/myrepo

https://docs.openshift.com/container-platform/4.16/openshift_images/image-configuration.html

https://github.com/containers/image/blob/main/docs/containers-registries.conf.5.md#choosing-a-registry-toml-table

2024-08-19 03:43 UTC, lwan-wanglin commented on pkg/systemconfig/syncer.go
> +			if mrc, ok := s.registriesConfContent.getRegistryConf(strings.Split(mirror.Location, "/")[0]); ok && mrc.Insecure != nil {
in my today's testing, changing to using pointer fixed the previous found issue, we also need to fix above @aleskandro's comments.

2024-08-20 15:46 UTC, aleskandro commented on pkg/systemconfig/types.go
> +func (rsc *registriesConf) newMirrorRegistries(locations []string, pullType PullType, registriesConf []*registryConf) []*Mirror {
we don't need anymore `registriesConf` as a parameter, right?

2024-08-20 15:46 UTC, aleskandro commented on pkg/systemconfig/types.go
> +func (rsc *registriesConf) isLocationInsecure(mirror string, registriesConf []*registryConf) *bool {
Same as the previous, do we still need to pass `registriesConf` as a parameter?

Also, as you call the method `isLocationInsecure`, I'd suggest changing the parameter name from `mirror` to `location`.

Finally, given we have a dedicated function that returns whether a registry is insecure or not, I would instead return a bool value, not a pointer, and then, in mirrorFor, we can add 

```
var insecurePtr *bool := nil
if insecure {
  insecurePtr = &insecure
}
```

`isLocationInsecure` can be used later for other reasons, while the true vs nil behavior is strictly related to the Toml marshaling. Returning `nil` with the meaning of `false` is very specific to the marshaling issue and doesn't respond/fit with the name of the method for me.

2024-08-20 15:46 UTC, aleskandro commented on pkg/systemconfig/syncer.go
> +	rc.Mirrors = s.registriesConfContent.newMirrorRegistries(mirrors, pullType, s.registriesConfContent.Registries)
How does `buildMirrorRegistries` or `makeMirrorRegistries` sound to you compared to `newMirrorRegistries`? the prefix `new` is widely used for initializing pointers and gives that idea: `newMirrorRegistries` does more than initializing the list.

2024-08-20 15:46 UTC, aleskandro commented on pkg/systemconfig/types.go
> +		if matchRegistry(mirror, rc.Location) && rc.Insecure != nil && rc.Insecure != &falseValue {
```suggestion
		if matchRegistry(mirror, rc.Location) && rc.Insecure != nil && *rc.Insecure != false {
```

You can't compare the two by address as they will always be different values (memory addresses)

2024-08-20 20:47 UTC, Prashanth684 commented on pkg/systemconfig/types.go
> +func matchPath(mirrorPath, registryPath string) bool {
can we just use regexes for these?

2024-08-21 21:56 UTC, closed without merging